@baseUrl = http://localhost:3333

# @name create_polls
POST {{baseUrl}}/polls
Content-Type: application/json

{
  "title": "Qual melhor framework do node.js?",
  "options": ["Express", "Fastify", "Nest"]
}

###

# @name get_details_poll
GET {{baseUrl}}/polls/details/clsb5v4wm00008su13wpgarh1
Content-Type: application/json

